### ISSUE TITLE
Syntax Docs - Code Smells (Code Review)

### ISSUE THREAD

**Issue by Abdirazak140** [KaranpreetRaja/SyntaxSage#53]
Problem report number #BR3
• Reported by Abdirazak Yusuf
• Date reported 27-03-2023
• Program: SyntaxDoc.java
Release number: v0.2.1
Version (build) identifier: https://github.com/KaranpreetRaja/SyntaxSage/commit/e56021098cb795bae21a2a8c4b86183ea83c378b

Magic Numbers:
I have found hardcoded values such as 700, 450, 200, and 10. For instance, we have setMinimumSize(new java.awt.Dimension(700, 450));. The significance of these values is unclear. The designer should have used descriptive names.

Long Method:
The SyntaxDoc(String language) constructor is extremely long and performs multiple tasks, including creating UI components and setting up action listeners.

Exposed Internals:
The instance variables LANGUAGES and LANGUAGE_URLS are static and public, allowing other classes to access them. Changing them to private would prevent unauthorized access.

Data Clumps:
Instance variables LANGUAGES and LANGUAGE_URLS are similar and could cause confusion or issues. I suggest using a data structure like a HashMap or creating a custom class.

Lack of Proper Error Handling:
No exception handling is present for the loadPage method.

Incomplete Code:
The second component of the user story is not implemented, indicating incomplete code.

**Comment by mahfoozm** [comment]
Changes implemented: Replacing magic numbers with variables (WIDTH, HEIGHT, HOME_URL), shuffling around from SyntaxDoc to loadPage, changing instance variables LANGUAGES and LANGUAGES_URLS to private, wrapping loadPage in a try catch to allow for error handling, and implementing the second component of the user story.
