### ISSUE TITLE
Syntax Testing - Code Smells (Code Review)

### ISSUE THREAD

**Issue by KaranpreetRaja** [KaranpreetRaja/SyntaxSage#57]
- **Problem report number:** #BR007
- **Reported by:** Karanpreet Raja
- **Date reported:** Mar 26, 2023
- **Program (or component) name:** Syntax Testing
- **Release number:** v0.2.1
- **Version (build) identifier:** e560210
- **Configuration(s):** Ubuntu 22.04 LTS, Java 8
- **Report type:** Design Issue
- **Can reproduce:** Yes (Design Issue)
- **Severity:** Medium
- **Priority:** High
- **Problem summary:** Many code smells in the Syntax Testing big user story implementation
- **Keywords:** Primitive Obsession, Uncommunicative Names, Lazzy Class, Data Clumps, Uncommunicative Names, Magic Numbers, Duplicate Code
- **Problem description and how to reproduce it:**

    - SelectionButton.java File:
        - Primitive Obsession: "Boolean isSelected” primitive can be encapsulated together in an object with its other components
        - Inconsistent Names: We have variable names “isSelected” and “isSelected()” which can cause confusion
        - Uncommunicative Names: “SelectionButton” should be a different name considering it doesn’t really explain what the class actually is first hand.
  
    - Question.java File:
        - Lazy Class: It is clear when observing the class that it is meant to act as the OOP backed of the Syntax Testing, however, it is not actually implemented and thus servers no purpose until it is added to SelectionButton
        - Data Clumps: Too many getters and setters makes the code harder to understand, it should be organise in a more better way such as using a class
        - Uncommunicative Names: We have “getNoAns()” and “noAns” which is quite hard to understand what the method and variable does, perhaps change it to “getNumberAns()” for instance.
          
    - SelectionButton.java and MultipleChoiceButton.java File:
        - Oddball Solution and Inappropriate Intimacy: MultipleChoiceButton Extends from the SelectionButton class which makes understanding the two classes hard
        - Magic Numbers: The color values should be customisable for the buttons and not just set to a default color when the button is selected or not selected
        - Missing Comments: Almost no comments exist for this class, and thus the functionality of the class is quite confusing.

- **Suggested fix:**

  - Long Method: Refactor into many smaller, and more specialised methods.
  - Magic Numbers: Replace with easily changeable constants.
  - Lazy Class: Remove unused class or integrate it properly with the rest of the user story (recommended).
  - Missing Comments: Add comments to describe the functionality of the classes that are missing them.
  - Data Clumps: Remove unnecessary setters and getters that are never used
  - Uncommunicative Names: Either change names of functions and attributes to better describe the functionality or add a comment explaining the name during initialisation
  - Inappropriate Intimacy: Rewrite some code instead of using inheritance if it makes the class's functionality clearer and the majority of the code is not similar.
  - Primitive Obsession: encapsulate with the object instead of using primitives 

- **Status:** Open
- **Resolution:** Pending
- **Resolved by:** N/A

**Comment by mahfoozm** [comment]
To fix the reported code smells, I created a new "Answer" class that contains answer-related methods. I also renamed the noAns variable and its getter method to be more communicative.
