### ISSUE TITLE
Badges and Awards - Bug Report (Code Review)

### ISSUE THREAD

**Issue by EarmuffSlime** [KaranpreetRaja/SyntaxSage#58]
**Program (or Component) Name:** BadgeGUI.java
**Release Number:** v0.2.1
**Bug Severity:** Trivial
**Bug Priority:** Minor

**Problem Summary:** All badges do not update fully when updating badges
**Steps to Reproduce:** Create a new account, progress in badges, and update badges in the dashboard

**Comment by mahfoozm** [comment]
By refactoring the BadgeGUI class, the badge implementation is now much more consistent (See #59).
