### ISSUE TITLE
BadgeGUI - Code Smells (Code Review)

### ISSUE THREAD

**Issue by EarmuffSlime** [KaranpreetRaja/SyntaxSage#59]
**Program (or Component) Name:** BadgeGUI.java
**Release Number:** v0.2.1 
**Problem Summary;** Code Smells in BadgeGUI class

**Large Class (Bloater)**

- The entire class is 1 large constructor, that is all
- Limitation of java swing and potentially fixable using other libraries (Not viable for this project)

**Long Method (Bloater)**

- Elements in the action listener should be moved outside of the constructor in order to promote reusability when the addition of other languages will be factored into the method
- Potentially replaceable by an extraction method with custom exception throws in order to streamline the process rather than hard code

**Long Parameter List (Bloater)**

- Badges and BadgeGUI can be made into separate classes which greatly decreases the size of the code in the badge GUI class as well as many useless parameters which are just reused

**Primitive Obsession (Bloater)**

- Use of constants for holding the badge default sizes

**Comments (Dispensable)**

- The comments or rather a lack thereof make the program difficult to read and understand without an existing understanding of the java swing library.

**Lazy Class (Dispensable)**

- This class is built to support future functionality but in its current state it simply must be redone almost entirely in order to provide functionality outside its current limitations

**Comment by mahfoozm** [comment]
This issue was fixed by rewriting BadgeGUI to fix these code smells (see commit ID 278b234)
