### ISSUE TITLE
Syntax Testing - Bug Report (End-2-End Test)

### ISSUE THREAD

**Issue by KaranpreetRaja** [KaranpreetRaja/SyntaxSage#60]
## Test Cases to Replicate Issue:
> Syntax Testing
> - Sign in with test account (user: test, pass: test). Launch session. When a multiple select window pops up, try selecting the two correct answers displayed on the window. Click submit button.
> - Sign in with test account (user: test, pass: test). Launch session. When a multiple choice window pops up, try selecting the one correct answer displayed on the window. Click submit button.
> - Sign in with test account (user: test, pass: test). Launch session. When a multiple select window pops up, try selecting one correct answer displayed on the window. Click submit button. It should say answer is partially correct.
> - Sign in with test account (user: test, pass: test). Launch session. When a multiple choice window pops up, try selecting an incorrect answer displayed on the window. Click submit button. It should display incorrect answer.

## Issue Report:
- **Problem report number:** #BR004
- **Reported by:** Karanpreet Raja
- **Date reported:** Mar 26, 2023
- **Program (or component) name:** Syntax Testing
- **Release number:** v0.2.1
- **Version (build) identifier:** e560210
- **Configuration(s):** Ubuntu 22.04 LTS, Java 8
- **Report type:** Design Issue
- **Can reproduce:** Yes (Design Issue)
- **Severity:** Medium
- **Priority:** Medium
- **Problem summary:** Reoccuring Questions
- **Keywords:** 
- **Problem description and how to reproduce it:**
    - Sign in with test account (user: test, pass: test). Launch session. Navigate through the questions and there is a good chance that you will be prompted with the same question multiple times. If this does not occur the first time you run a session, repeat the process.
- **Suggested fix:** Utalize the Question class which is already built and modify it such that it pre selects all the questions that will be prompted to the user in a session. When constructing the "Array" of questions, make sure when appending a question, make sure that the question does not already exist within the array.
- **Status:** Open
- **Resolution:** Pending
- **Resolved by:** N/A

**Comment by mahfoozm** [comment]
This was fixed by changing the MySQL database table to grab questions in order to prevent duplicate questions from being served to the user.
