### ISSUE TITLE
Syntax Docs - Bugs (Code Review)

### ISSUE THREAD

**Issue by Abdirazak140** [KaranpreetRaja/SyntaxSage#61]
Problem report number #BR3
• Reported by Abdirazak Yusuf
• Date reported 27-03-2023
• Program: SyntaxDoc.java
Release number: v0.2.1
Version (build) identifier: https://github.com/KaranpreetRaja/SyntaxSage/commit/e56021098cb795bae21a2a8c4b86183ea83c378b

CSS Navigation Bug:
There is a bug in the code as it does not display the CSS document on the left panel. This issue might be due to an incorrect address/URL.

**Comment by mahfoozm** [comment]
This was fixed by parsing markdown and rendering to HTML instead of grabbing HTML and attempting to render that directly (see commit ID 035de96)
